/**
 * Ed25519 signature verification for license keys.
 *
 * The public key is supplied as an environment variable (never hardcoded).
 * Two encodings are accepted:
 *  - A raw 32-byte Ed25519 public key, base64-encoded (the recommended,
 *    compact env-var-friendly format).
 *  - A full PEM-encoded SPKI public key (useful when generated by common
 *    tooling such as `openssl genpkey -algorithm ed25519`).
 */
import { createPublicKey, verify as cryptoVerify, type KeyObject } from 'node:crypto';

// DER prefix for an Ed25519 SubjectPublicKeyInfo structure. Concatenating this
// with the 32 raw public key bytes yields a complete, valid SPKI DER blob.
const ED25519_SPKI_DER_PREFIX = Buffer.from('302a300506032b6570032100', 'hex');
const ED25519_RAW_KEY_LENGTH = 32;

export function loadEd25519PublicKey(publicKeyMaterial: string): KeyObject {
  const trimmed = publicKeyMaterial.trim();

  if (trimmed.startsWith('-----BEGIN')) {
    return createPublicKey(trimmed);
  }

  const raw = Buffer.from(trimmed, 'base64');
  if (raw.length !== ED25519_RAW_KEY_LENGTH) {
    throw new Error(
      `Invalid Ed25519 public key: expected ${ED25519_RAW_KEY_LENGTH} raw bytes (base64-encoded), got ${raw.length}`,
    );
  }

  const der = Buffer.concat([ED25519_SPKI_DER_PREFIX, raw]);
  return createPublicKey({ key: der, format: 'der', type: 'spki' });
}

export function verifyEd25519Signature(
  payload: Uint8Array,
  signature: Uint8Array,
  publicKeyMaterial: string,
): boolean {
  const key = loadEd25519PublicKey(publicKeyMaterial);
  try {
    return cryptoVerify(null, payload, key, signature);
  } catch {
    // A malformed signature buffer throws rather than returning false in
    // node:crypto — normalize to a boolean result for callers.
    return false;
  }
}
