#!/usr/bin/env bun
/**
 * Local demo/dev bootstrap script.
 *
 * Generates a throwaway .env with a valid license, JWT keypair, local admin
 * user (argon2id hash), and a real `dolt init`-ed repo — so a contributor
 * can `bun run dev` immediately without hand-crafting any secrets.
 *
 * Reuses the same test fixtures the automated test suite trusts
 * (tests/fixtures/license-fixtures.ts), so this script stays correct as the
 * license/JWT formats evolve instead of drifting out of sync.
 *
 * NOT for production use. NEVER commit the generated .env or dolt repo.
 */
import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { $ } from 'bun';
import { hashPassword } from '../src/contexts/auth/password-authenticator';
import {
  buildDefaultPayload,
  generateTestJwtKeypairPem,
  generateTestKeypair,
  signLicensePayload,
} from '../tests/fixtures/license-fixtures';

const ADMIN_USERNAME = 'admin';
const ADMIN_PASSWORD = 'demo1234';

async function main() {
  const repoPath = await mkdtemp(join(tmpdir(), 'deltix-local-demo-dolt-'));
  await $`dolt config --global --add user.name deltix-demo`.quiet().nothrow();
  await $`dolt config --global --add user.email deltix-demo@example.com`.quiet().nothrow();
  await $`dolt --data-dir ${repoPath} init`.quiet().nothrow();

  const { publicKeyBase64, privateKeyPem: licensePrivateKeyPem } = generateTestKeypair();
  const licenseKey = signLicensePayload(buildDefaultPayload(), licensePrivateKeyPem);
  const { privateKeyPem: jwtPrivateKeyPem, publicKeyPem: jwtPublicKeyPem } =
    generateTestJwtKeypairPem();

  const passwordHash = await hashPassword(ADMIN_PASSWORD);
  const localUsers = JSON.stringify([{ username: ADMIN_USERNAME, passwordHash }]);

  const sessionDbPath = join(tmpdir(), 'deltix-local-demo-sessions.db');

  const escapeNewlines = (pem: string) => pem.trim().replace(/\n/g, '\\n');

  const env = `# Auto-generated by scripts/setup-local-demo.ts — DO NOT COMMIT.
NODE_ENV=development
HTTP_PORT=9090
GRPC_DOLT_PORT=50051
LOG_LEVEL=info
LOG_PRETTY=true

DELTIX_LICENSE_PUBLIC_KEY=${publicKeyBase64}
DELTIX_LICENSE_KEY=${licenseKey}
DELTIX_DOLT_REPO_PATH=${repoPath}
DELTIX_CLOCK_TOLERANCE_MS=5000

DELTIX_JWT_PRIVATE_KEY="${escapeNewlines(jwtPrivateKeyPem)}"
DELTIX_JWT_PUBLIC_KEY="${escapeNewlines(jwtPublicKeyPem)}"
DELTIX_LOCAL_USERS='${localUsers.replace(/\$/g, '\\$')}'
DELTIX_SESSION_DB_PATH=${sessionDbPath}
DELTIX_ACCESS_TOKEN_TTL_SECONDS=900
DELTIX_SESSION_TTL_SECONDS=120
DELTIX_CORS_ALLOWED_ORIGINS=http://127.0.0.1:9090
DELTIX_ADMIN_UI_ENABLED=true
`;

  await Bun.write('.env', env);
}

main();
